name: lint # ci文件的名字
on: 
  push # 触发CI的条件
jobs: 
  preview:
    name: lint
    runs-on: ubuntu-latest
    steps: 
    - name: addnode # ESLint 检测代码质量
      uses: actions/setup-node@v3 # 使用node环境
      with:
        node-version: 18
    - name: addpackage
      run: yarn
    - name: run-preview
      run: yarn preview