name: build
on: workflow_dispatch
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: add package
        run: yarn
      - name: build
        run: yarn build
