name: lint # ci文件的名字
on: 
  push # 触发CI的条件
jobs: 
  add-package:
    name: add-package
    runs-on: ubuntu-latest
    steps: 
    - name: addnode # ESLint 检测代码质量
      uses: actions/setup-node@v2 # 使用node环境