name: lint # ci文件的名字
on: 
  push # 触发CI的条件
jobs: 
  add-node:
    name: add-node
    runs-on: ubuntu-latest
    steps: 
    - name: addnode # ESLint 检测代码质量
      uses: actions/setup-node@v2 # 使用node环境
  add-package:
    name: add-package
    runs-on: ubuntu-latest
    needs: add-node
    steps:
      - name: addpackage
        run: yarn
  preview:
    name: preview
    runs-on: ubuntu-latest
    needs: [add-node, add-package]
    steps:
      - name: preview
        run: yarn preview